// components/pdf/TransactionReceiptPDF.tsx
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer"
import type { Transaction } from "@/types"
import { formatCurrency, formatDate } from "@/lib/utils/utils"

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: "Helvetica",
    position: "relative",
    backgroundColor: "#fff",
  },
  watermark: {
    position: "absolute",
    top: "35%",
    left: "10%",
    opacity: 0.05,
    fontSize: 100,
    transform: "rotate(-30deg)",
    color: "#000",
  },
  logo: {
    width: 100,
    marginBottom: 10,
  },
  headerText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  subHeader: {
    fontSize: 14,
    color: "#555",
    marginBottom: 15,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 6,
    color: "#222",
    borderBottom: "1 solid #ccc",
    paddingBottom: 4,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  label: {
    fontWeight: "bold",
    color: "#333",
  },
  footer: {
    marginTop: 30,
    textAlign: "center",
    fontSize: 10,
    color: "#999",
  },
})

export default function TransactionReceiptPDF({
  transaction,
  logoUrl,
}: {
  transaction: Transaction
  logoUrl?: string
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.watermark}>RAHASIA</Text>

        {logoUrl && <Image style={styles.logo} src={logoUrl} />}

        <Text style={styles.headerText}>PT IMAM MANTAP</Text>
        <Text style={styles.subHeader}>Transaction Receipt</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Transaction Info</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Date:</Text>
            <Text>{formatDate(transaction.date)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Description:</Text>
            <Text>{transaction.description}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Amount:</Text>
            <Text>{formatCurrency(transaction.amount)}</Text>
          </View>
          {transaction.fee && (
            <View style={styles.row}>
              <Text style={styles.label}>Fee:</Text>
              <Text>{formatCurrency(transaction.fee)}</Text>
            </View>
          )}
          {transaction.total_amount && (
            <View style={styles.row}>
              <Text style={styles.label}>Total:</Text>
              <Text>{formatCurrency(transaction.total_amount)}</Text>
            </View>
          )}
          <View style={styles.row}>
            <Text style={styles.label}>Reference:</Text>
            <Text>{transaction.reference || '-'}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Account Info</Text>
          <View style={styles.row}>
            <Text style={styles.label}>From:</Text>
            <Text>{transaction.account_from || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>To:</Text>
            <Text>{transaction.account_to || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Provider:</Text>
            <Text>{transaction.provider || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Merchant:</Text>
            <Text>{transaction.merchant || '-'}</Text>
          </View>
        </View>

        {transaction.note_to_user && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Note</Text>
            <Text>{transaction.note_to_user}</Text>
          </View>
        )}

        <Text style={styles.footer}>Generated by PT IMAM MANTAP • Confidential Document</Text>
      </Page>
    </Document>
  )
}
